version: "3"
services:
  reverseproxy:
      image: noreenwu/reverseproxy:v7
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed
  backend-user:
    image: noreenwu/udagram-api-user:v7
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
      POSTGRES_DB: $POSTGRES_DB 
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION 
      AWS_PROFILE: $AWS_PROFILE 
      AWS_BUCKET: $AWS_BUCKET_USER
      JWT_SECRET: $JWT_SECRET
      URL: "ab22489b0b74a48dc98421741fce8bd8-1175957389.us-east-2.elb.amazonaws.com"
  backend-feed:
    image: noreenwu/udagram-api-feed:v22
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE 
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "ab22489b0b74a48dc98421741fce8bd8-1175957389.us-east-2.elb.amazonaws.com"
  frontend:
    image: noreenwu/udagram-frontend:v10
    ports:
      - "80:80"