apiVersion: apps/v1
kind: Deployment
metadata:
  name: publicreverseproxy
  labels:
    service: publicreverseproxy  
spec:
  replicas: 1
  selector:
    matchLabels:
      service: publicreverseproxy
  template:
    metadata:
      labels:
        service: publicreverseproxy
    spec:
      containers:
      - image: noreenwu/reverseproxy
        name: publicreverseproxy
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
      restartPolicy: Always